// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// loglikelihood_cpp
double loglikelihood_cpp(arma::vec gamma_hat, arma::mat Gamma_hat, arma::mat R, int n1, int n2, arma::vec theta);
RcppExport SEXP _MRMOSS_loglikelihood_cpp(SEXP gamma_hatSEXP, SEXP Gamma_hatSEXP, SEXP RSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type gamma_hat(gamma_hatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma_hat(Gamma_hatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(loglikelihood_cpp(gamma_hat, Gamma_hat, R, n1, n2, theta));
    return rcpp_result_gen;
END_RCPP
}
// MRMOSS_PX_cpp
List MRMOSS_PX_cpp(arma::vec gamma_hat, arma::mat Gamma_hat, arma::mat R, int n1, int n2, arma::vec theta0, arma::uvec test, int maxiter);
RcppExport SEXP _MRMOSS_MRMOSS_PX_cpp(SEXP gamma_hatSEXP, SEXP Gamma_hatSEXP, SEXP RSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP theta0SEXP, SEXP testSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type gamma_hat(gamma_hatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Gamma_hat(Gamma_hatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type test(testSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(MRMOSS_PX_cpp(gamma_hat, Gamma_hat, R, n1, n2, theta0, test, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MRMOSS_loglikelihood_cpp", (DL_FUNC) &_MRMOSS_loglikelihood_cpp, 6},
    {"_MRMOSS_MRMOSS_PX_cpp", (DL_FUNC) &_MRMOSS_MRMOSS_PX_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_MRMOSS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
