# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglikelihood_cpp <- function(gamma_hat, Gamma_hat, R, n1, n2, theta) {
    .Call(`_MRMOSS_loglikelihood_cpp`, gamma_hat, Gamma_hat, R, n1, n2, theta)
}

MRMOSS_PX_cpp <- function(gamma_hat, Gamma_hat, R, n1, n2, theta0, test, maxiter, rd) {
    .Call(`_MRMOSS_MRMOSS_PX_cpp`, gamma_hat, Gamma_hat, R, n1, n2, theta0, test, maxiter, rd)
}

